version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email  --region eu-west-1 )
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t ecs-demo .
      - docker tag ecs-demo:latest 392706139484.dkr.ecr.eu-west-1.amazonaws.com/ecs-demo:latest     
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 392706139484.dkr.ecr.eu-west-1.amazonaws.com/ecs-demo:latest